active_model: dlib_hog
presets:
  dlib_hog:
    library: dlib
    model: hog
    resize_width: 450
    clustering:
      eps: 0.45
      metric: euclidean
      min_samples: 2
  dlib_cnn:
    library: dlib
    model: cnn
    resize_width: 800
    clustering:
      eps: 0.42
      metric: euclidean
      min_samples: 2
  deepface_vgg:
    library: deepface
    embedding_model: VGG-Face
    detector: retinaface
    resize_width: N/A
    clustering:
      eps: 0.45
      min_samples: 2
      metric: cosine
  deepface_facenet:
    library: "deepface"
    embedding_model: "Facenet"
    detector: "retinaface"
    resize_width: N/A
    clustering:
      eps: 0.8 # A good starting point for FaceNet
      metric: "euclidean"
      min_samples: 2

# ADD THIS NEW SECTION
postgresql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "Samarth02@postgres"
  dbname: "face_gallery"

directory_paths:
  source: source_images
  output: output_sorted
  log_file: run_log.txt
  ground_truth: ground_truth.json
  gallery_storage: gallery_storage

output_settings:
  folder_prefix: Person_
  unknowns_folder: Unknowns